
file(READ "${CMAKE_CURRENT_LIST_DIR}/_libQL.sources" USER_QLLIB_PYBIND_SOURCES)
STRING(REGEX REPLACE ";" "\\\\;" USER_QLLIB_PYBIND_SOURCES "${USER_QLLIB_PYBIND_SOURCES}")
STRING(REGEX REPLACE "\n" ";" USER_QLLIB_PYBIND_SOURCES "${USER_QLLIB_PYBIND_SOURCES}")
list(TRANSFORM USER_QLLIB_PYBIND_SOURCES PREPEND "${CMAKE_CURRENT_LIST_DIR}/")

